### PR TITLE
fix: Update aws provider version to restore support for ignore_header_row

### PR DESCRIPTION
**Pull request by scadu**
## Description

Terraform provider in [version 4.49.0 gets a fix](https://github.com/hashicorp/terraform-provider-aws/pull/28579) that allows setting `IgnoreHeaderRows`, with a fallback on `ignore_header_row` besides `ignore_header_rows`.
In version [5.0.0 of the provider, the fallback is removed ](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0) and there are many other breaking changes that affects this module and underlying VPC module.

## Motivation and Context

Fixes https://github.com/terraform-aws-modules/terraform-aws-dms/issues/38

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by scadu** [comment]
I have no idea why the PR title action fails, even though the title is fine. Looks like the fix prefix isn’t detected for some reason.

**Comment by scadu** [comment]
> So, I checked the PR files and I realized there is no fix for the Ignore Rows itself, but limiting the terraform to 5.0. I have other terraform-aws they already upgraded the constraints to >5.0.0 and that force me to move to a newer version.
> 
> Anyway, thanks for the prompt answer.

I will try to take a look and adjust the module, so it's compatible with aws provider 5.0.0 and above. Let's see.

**Comment by scadu** [comment]
With the current example, https://github.com/clowdhaus/terraform-aws-msk-kafka-cluster/pull/4 would need to get merged as  EBS-related configuration for [aws_msk_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster.html) resource were also moved.

**Comment by igorjanevski** [comment]
Can you guys provide ETA for the fix? We are stuck with this and need it to work with 5.0

**Comment by brunodasilvalenga** [comment]
Hey guys, any chances to someone approve the PR?

**Comment by scadu** [comment]
Looks like https://github.com/terraform-aws-modules/terraform-aws-dms/pull/42 is the more complete one, but it's marked as a draft for now.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.0.0 :tada:

**Pull request closed without merging**
