### PR TITLE
fix: Fixes small README typos

### PR DESCRIPTION
**Pull request by saralein**
## Description
This PR fixes two small typos in the repository README.

## Motivation and Context
These distracted me slightly while reading through this paragraph, and I wanted to provide smoother reading for others.

## Breaking Changes
None.

### CODE REVIEW

**Comment by saralein** [comment]
Possible update to PR title: `docs` or `fix`? Assuming perhaps `docs` but leaving for the moment.

**Comment by bryantbiggs** [comment]
@saralein it looks like I can't update your branch - I've opened a PR that once you add in those changes the checks should pass and we can merge this in https://github.com/saralein/terraform-aws-dms/pull/1

**Review by bryantbiggs — APPROVED** [review]
thank you!

**Comment by saralein** [comment]
> @saralein it looks like I can't update your branch - I've opened a PR that once you add in those changes the checks should pass and we can merge this in [saralein#1](https://github.com/saralein/terraform-aws-dms/pull/1)

Thank you very much. I believe I was mucking around with settings over there, thinking no one would need to mess with it.

**Comment by antonbabenko** [comment]
This PR is included in version 2.0.0 :tada:

**Pull request merged**
